// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6iShOHehl9fXoc_HGryt_BIJgm0Rx2BQ',
    appId: '1:1068677795819:web:6b0e9ddeebae6353ce53ae',
    messagingSenderId: '1068677795819',
    projectId: 'moviesapp-e95f9',
    authDomain: 'moviesapp-e95f9.firebaseapp.com',
    storageBucket: 'moviesapp-e95f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvAQzN-rDrUNmgqSEVLLX26HuDCPKDaS4',
    appId: '1:1068677795819:android:663888cc1300bab3ce53ae',
    messagingSenderId: '1068677795819',
    projectId: 'moviesapp-e95f9',
    storageBucket: 'moviesapp-e95f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5h816xLza50TDmRahVCtMGfhJhrUbBE',
    appId: '1:1068677795819:ios:e18a6613dcd8b71dce53ae',
    messagingSenderId: '1068677795819',
    projectId: 'moviesapp-e95f9',
    storageBucket: 'moviesapp-e95f9.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5h816xLza50TDmRahVCtMGfhJhrUbBE',
    appId: '1:1068677795819:ios:e18a6613dcd8b71dce53ae',
    messagingSenderId: '1068677795819',
    projectId: 'moviesapp-e95f9',
    storageBucket: 'moviesapp-e95f9.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6iShOHehl9fXoc_HGryt_BIJgm0Rx2BQ',
    appId: '1:1068677795819:web:d615d8af0a8ec993ce53ae',
    messagingSenderId: '1068677795819',
    projectId: 'moviesapp-e95f9',
    authDomain: 'moviesapp-e95f9.firebaseapp.com',
    storageBucket: 'moviesapp-e95f9.appspot.com',
  );
}
